<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/bootstrap-select/bootstrap-select.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/select2/select2.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/flatpickr/flatpickr.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/typeahead-js/typeahead.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/tagify/tagify.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/@form-validation/form-validation.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/animate-css/animate.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/sweetalert2/sweetalert2.css" />
<link rel="stylesheet" href="{{ asset('dashboard') }}/assets/vendor/libs/dropzone/dropzone.css" />
